drop all objects;

create table if not exists users (
    id integer generated by default as identity primary key,
    email varchar(50) not null,
    login varchar(50) not null,
    name varchar(50),
    birthday date not null
    );

create table if not exists friends (
    user_id integer not null references users (id),
    friend_id integer not null references users (id)
    );

create table if not exists mpa (
    id integer generated by default as identity primary key,
    name varchar(5) not null
    );

create table if not exists genres (
    id integer generated by default as identity primary key,
    name varchar(50) not null
    );

create table if not exists films (
    id integer generated by default as identity primary key,
    name varchar(100) not null,
    description varchar(200) not null,
    release_date date not null,
    duration integer not null,
    rating_id integer references mpa (id)
    );

create table if not exists film_genre (
    film_id integer not null references films (id) on delete cascade,
    genre_id integer not null references genres (id)
    );

create table if not exists likes (
    film_id integer not null references films (id),
    user_id integer not null references users (id),
    constraint likes_pk primary key (film_id, user_id)
    );



